#!/bin/bash

# 修复环境ID问题脚本

echo "🔧 修复 CloudBase 环境ID无效问题"
echo "================================="

# 读取当前配置
CURRENT_ENV=$(grep -o '"envId": *"[^"]*"' cloudbaserc.json | head -1 | cut -d'"' -f4)
echo "当前配置的环境ID: '$CURRENT_ENV'"

echo ""
echo "📋 问题诊断:"
echo "   错误 'Env invalid' 表示:"
echo "   1. 环境 '$CURRENT_ENV' 不存在"
echo "   2. 或者你没有该环境的访问权限"
echo "   3. 或者环境ID拼写错误"

echo ""
echo "🚀 解决方案:"

echo ""
echo "选项1: 查看现有环境并选择"
echo "-------------------------"
echo "执行以下命令查看你的所有环境:"
echo "  cloudbase env:list"
echo ""
echo "然后从列表中选择一个环境ID，更新配置文件:"
echo "  sed -i '' 's/\"envId\": \".*\"/\"envId\": \"YOUR-ACTUAL-ENV-ID\"/' cloudbaserc.json"

echo ""
echo "选项2: 创建新环境"
echo "----------------"
echo "如果你想创建新环境 'test-platform-env':"
echo "  cloudbase env:create test-platform-env"
echo ""
echo "创建后，环境会自动配置，可以使用默认配置"

echo ""
echo "选项3: 使用默认环境"
echo "------------------"
echo "CloudBase 通常有一个默认环境，可能是:"
echo "  - 你的用户名相关"
echo "  - 或第一个创建的环境"
echo ""
echo "常见默认环境名:"
echo "  - default"
echo "  - dev"
echo "  - prod"
echo "  - staging"
echo "  - 你的用户名 (如: zhangyongcheng)"

echo ""
echo "🔧 快速修复步骤:"
echo ""
echo "1. 查看环境列表:"
echo "   cloudbase env:list"
echo ""
echo "2. 选择一个环境 (例如 'default'):"
echo "   sed -i '' 's/\"envId\": \".*\"/\"envId\": \"default\"/' cloudbaserc.json"
echo ""
echo "3. 验证环境:"
echo "   cloudbase env:info default"
echo ""
echo "4. 测试部署:"
echo "   cloudbase hosting:deploy frontend/dist -e default"
echo ""
echo "📝 配置文件 cloudbaserc.json 应该包含:"
echo "   \"envId\": \"your-actual-env-id\","
echo "   \"region\": \"ap-shanghai\","

echo ""
echo "⚠️  如果仍然有问题，请检查:"
echo "   1. CloudBase 账号是否有权限"
echo "   2. 区域是否正确 (ap-shanghai)"
echo "   3. 环境状态是否正常"
echo ""
echo "🔗 CloudBase 控制台 (手动检查):"
echo "   https://console.cloud.tencent.com/tcb"
echo ""
echo "📞 如果需要帮助，请提供:"
echo "   1. 'cloudbase env:list' 的输出"
echo "   2. 你想使用的环境名"